TEMPLATE ::= LESSTHAN TAGNAME GREATERTHAN  BODY  LESS_THAN_SLASH TAGNAME GREATERTHAN
BODY ::= ELEMENT *
ELEMENT ::= LESSTHAN TAGNANE  ATTRIBUTE-LIST * GREATERTHAN  (ELEMENT | TEXT | CHL-PLACEHOLDER )  LESS_THAN_SLASH TAGNANE GREATERTHAN
CHL-PLACEHOLDER ::= PLACEHOLDER_END_SYMBOL CHL-PLACEHOLDER-NAME PLACEHOLDER_START_SYMBOL
CHL-PLACEHOLDER-NAME ::= CHAR *
ATTRIBUTE-LIST ::= ATTRIBUTE *
ATTRIBUTE ::= ATTRKEY  EQUAL_SYMBOL  ATTRVALUE

ATTRVALUE ::=  APOSTROPHE CHAR * APOSTROPHE
LESSTHAN ::= "<"
GREATERTHAN ::= ">"
LESS_THAN_SLASH ::= "</"

PLACEHOLDER_START_SYMBOL ::= "!{"
PLACEHOLDER_END_SYMBOL ::= "}!"
EQUAL_SYMBOL ::= "="
APOSTROPHE ::= "\'" | "\""
TAGNAME ::= 'chl-template'| 'chl-datamap' |  'div' | ... all html tags
ATTRKEY ::= 'chl-data' | 'chl-selector' | ...all html attributes
CHAR ::= any character except '"'



<div id="hero" />

char = Token:;


<div